"""task assigned user optional

Revision ID: 2eff05450155
Revises: 1e6426d7c3eb
Create Date: 2026-06-18 11:08:02.363507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eff05450155'
down_revision: Union[str, Sequence[str], None] = '1e6426d7c3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assigned_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assigned_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
